name: bspytasks
dependencies:
   - python=3.6
   - pip
   - pip:
     - git+https://github.com/BraiNEdarwin/brainspy-instruments.git
     - git+https://github.com/BraiNEdarwin/brainspy-algorithms.git
     - numpy
     - pandas
     - matplotlib
     - ipython
