type: 'gradient'
epochs: 60
batch_size: 256
worker_no: 0
learning_rate: 0.001
criterion: 'corrsig'
optimizer: 'adam'
stop_threshold: 0.0065
accuracy: # Configurations for the perceptron
  epochs: 100
  learning_rate: 0.0007
  betas: 
    !!python/tuple [0.999, 0.999]
  split: [1,0] # Training and validation data split in a range from 0 to 1
  mini_batch: 256