from_dimension: 4
to_dimension: 10
threshold_parameter: 0.5
max_attempts : 5
results_base_dir : "tmp/TEST/output/boolean"
algorithm: !include defaults/algorithms/ga/boolean.yaml
processor: !include defaults/processors/hw.yaml
