results_base_dir : "tmp/TEST/output/ring"
runs: 3
data:
  gap: 0.4
  load: false # If load is false, it generates a new dataset. If load is a path to the data, it loads it to the data
  sample_no: 900
  split_percentages: # The data is divided into training, validation and test datasets respectively
    - 0.9 # Percentage of the data used for training
    - 0.1 # Percentage of the data used for validation
    - 0 # Percentage of the data used for test
algorithm: !include defaults/algorithms/ga/ring.yaml
processor: !include defaults/processors/simulation.yaml
validation_processor: !include defaults/processors/hw.yaml